#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpGLWinformsApplication1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PlatformFlawBase")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void InsertStressInput(StressInput instance);
    partial void UpdateStressInput(StressInput instance);
    partial void DeleteStressInput(StressInput instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::SharpGLWinformsApplication1.Properties.Settings.Default.PlatformFlawBaseConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<StressInput> StressInput
		{
			get
			{
				return this.GetTable<StressInput>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.StressInput")]
	public partial class StressInput : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private System.Nullable<double> _kc11;
		
		private System.Nullable<double> _kc12;
		
		private System.Nullable<double> _kc13;
		
		private System.Nullable<double> _kc14;
		
		private System.Nullable<double> _kc21;
		
		private System.Nullable<double> _kc22;
		
		private System.Nullable<double> _kc23;
		
		private System.Nullable<double> _kc24;
		
		private System.Nullable<double> _kc31;
		
		private System.Nullable<double> _kc32;
		
		private System.Nullable<double> _kc4;
		
		private System.Nullable<double> _kc51;
		
		private System.Nullable<double> _kc52;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void Onkc11Changing(System.Nullable<double> value);
    partial void Onkc11Changed();
    partial void Onkc12Changing(System.Nullable<double> value);
    partial void Onkc12Changed();
    partial void Onkc13Changing(System.Nullable<double> value);
    partial void Onkc13Changed();
    partial void Onkc14Changing(System.Nullable<double> value);
    partial void Onkc14Changed();
    partial void Onkc21Changing(System.Nullable<double> value);
    partial void Onkc21Changed();
    partial void Onkc22Changing(System.Nullable<double> value);
    partial void Onkc22Changed();
    partial void Onkc23Changing(System.Nullable<double> value);
    partial void Onkc23Changed();
    partial void Onkc24Changing(System.Nullable<double> value);
    partial void Onkc24Changed();
    partial void Onkc31Changing(System.Nullable<double> value);
    partial void Onkc31Changed();
    partial void Onkc32Changing(System.Nullable<double> value);
    partial void Onkc32Changed();
    partial void Onkc4Changing(System.Nullable<double> value);
    partial void Onkc4Changed();
    partial void Onkc51Changing(System.Nullable<double> value);
    partial void Onkc51Changed();
    partial void Onkc52Changing(System.Nullable<double> value);
    partial void Onkc52Changed();
    #endregion
		
		public StressInput()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc11", DbType="Float")]
		public System.Nullable<double> kc11
		{
			get
			{
				return this._kc11;
			}
			set
			{
				if ((this._kc11 != value))
				{
					this.Onkc11Changing(value);
					this.SendPropertyChanging();
					this._kc11 = value;
					this.SendPropertyChanged("kc11");
					this.Onkc11Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc12", DbType="Float")]
		public System.Nullable<double> kc12
		{
			get
			{
				return this._kc12;
			}
			set
			{
				if ((this._kc12 != value))
				{
					this.Onkc12Changing(value);
					this.SendPropertyChanging();
					this._kc12 = value;
					this.SendPropertyChanged("kc12");
					this.Onkc12Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc13", DbType="Float")]
		public System.Nullable<double> kc13
		{
			get
			{
				return this._kc13;
			}
			set
			{
				if ((this._kc13 != value))
				{
					this.Onkc13Changing(value);
					this.SendPropertyChanging();
					this._kc13 = value;
					this.SendPropertyChanged("kc13");
					this.Onkc13Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc14", DbType="Float")]
		public System.Nullable<double> kc14
		{
			get
			{
				return this._kc14;
			}
			set
			{
				if ((this._kc14 != value))
				{
					this.Onkc14Changing(value);
					this.SendPropertyChanging();
					this._kc14 = value;
					this.SendPropertyChanged("kc14");
					this.Onkc14Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc21", DbType="Float")]
		public System.Nullable<double> kc21
		{
			get
			{
				return this._kc21;
			}
			set
			{
				if ((this._kc21 != value))
				{
					this.Onkc21Changing(value);
					this.SendPropertyChanging();
					this._kc21 = value;
					this.SendPropertyChanged("kc21");
					this.Onkc21Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc22", DbType="Float")]
		public System.Nullable<double> kc22
		{
			get
			{
				return this._kc22;
			}
			set
			{
				if ((this._kc22 != value))
				{
					this.Onkc22Changing(value);
					this.SendPropertyChanging();
					this._kc22 = value;
					this.SendPropertyChanged("kc22");
					this.Onkc22Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc23", DbType="Float")]
		public System.Nullable<double> kc23
		{
			get
			{
				return this._kc23;
			}
			set
			{
				if ((this._kc23 != value))
				{
					this.Onkc23Changing(value);
					this.SendPropertyChanging();
					this._kc23 = value;
					this.SendPropertyChanged("kc23");
					this.Onkc23Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc24", DbType="Float")]
		public System.Nullable<double> kc24
		{
			get
			{
				return this._kc24;
			}
			set
			{
				if ((this._kc24 != value))
				{
					this.Onkc24Changing(value);
					this.SendPropertyChanging();
					this._kc24 = value;
					this.SendPropertyChanged("kc24");
					this.Onkc24Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc31", DbType="Float")]
		public System.Nullable<double> kc31
		{
			get
			{
				return this._kc31;
			}
			set
			{
				if ((this._kc31 != value))
				{
					this.Onkc31Changing(value);
					this.SendPropertyChanging();
					this._kc31 = value;
					this.SendPropertyChanged("kc31");
					this.Onkc31Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc32", DbType="Float")]
		public System.Nullable<double> kc32
		{
			get
			{
				return this._kc32;
			}
			set
			{
				if ((this._kc32 != value))
				{
					this.Onkc32Changing(value);
					this.SendPropertyChanging();
					this._kc32 = value;
					this.SendPropertyChanged("kc32");
					this.Onkc32Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc4", DbType="Float")]
		public System.Nullable<double> kc4
		{
			get
			{
				return this._kc4;
			}
			set
			{
				if ((this._kc4 != value))
				{
					this.Onkc4Changing(value);
					this.SendPropertyChanging();
					this._kc4 = value;
					this.SendPropertyChanged("kc4");
					this.Onkc4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc51", DbType="Float")]
		public System.Nullable<double> kc51
		{
			get
			{
				return this._kc51;
			}
			set
			{
				if ((this._kc51 != value))
				{
					this.Onkc51Changing(value);
					this.SendPropertyChanging();
					this._kc51 = value;
					this.SendPropertyChanged("kc51");
					this.Onkc51Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kc52", DbType="Float")]
		public System.Nullable<double> kc52
		{
			get
			{
				return this._kc52;
			}
			set
			{
				if ((this._kc52 != value))
				{
					this.Onkc52Changing(value);
					this.SendPropertyChanging();
					this._kc52 = value;
					this.SendPropertyChanged("kc52");
					this.Onkc52Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
